## MEET THE SIGMOID FUNCTION

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np


In [3]:
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)


tensor([[0.9975]])


$$ ACTIVATION FUNCTION AS THE LAST LAYER

In [7]:
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    nn.Sigmoid()
)

print(model(torch.tensor([[1.0,2.0,3.0,4.0,5.0,6.0]])))

tensor([[0.5806]], grad_fn=<SigmoidBackward0>)


In [15]:
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

#Apply softmax along the last dimension
probalities = nn.Softmax(dim = -1)
output_tensor = probalities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


$$ Binary Classification: Forward pass

In [13]:
#create input data of shape 5x6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [-0.4436, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
    [0.2073, 0.8147, 0.4332, 0.2293, 0.4676, 0.6119],
    [-1.6630, -0.0781, -0.3324, 0.1924, -0.9659, -0.3479],
    [0.2073, 0.8147, 0.4332, 0.2293, 0.4676, 0.6119]]
)



In [14]:
output = model(input_data)
print(output)

tensor([[0.7136],
        [0.7136],
        [0.6499],
        [0.6511],
        [0.6499]], grad_fn=<SigmoidBackward0>)


$$ Multi-class classification: ForwardPass


In [16]:
n_class = 3

#Create a multiclass classification model
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,n_class),
    nn.Softmax(dim = -1)
)

output = model (input_data)
print(output)

tensor([[0.3031, 0.1993, 0.4976],
        [0.3031, 0.1993, 0.4976],
        [0.3233, 0.2530, 0.4237],
        [0.3688, 0.1932, 0.4380],
        [0.3233, 0.2530, 0.4237]], grad_fn=<SoftmaxBackward0>)


In [17]:
output.shape

torch.Size([5, 3])

 $$ Regression: ForwardPass

In [18]:
model = nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1),
    # nn.Sigmoid()
)

output = model (input_data)

print(output)

tensor([[ 0.3169],
        [ 0.3169],
        [ 0.0371],
        [-0.2143],
        [ 0.0371]], grad_fn=<AddmmBackward0>)
