# VÕ HỒNG VIỆT

# 22725461

In [2]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
 



In [5]:
lst =   [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tensor1 = torch.tensor(lst)

np_array = np.array(lst)
tensor2 = torch.from_numpy(np_array)

In [6]:
print(tensor1)
print(tensor2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
print(tensor1+ tensor2)
print(tensor1- tensor2)
print(tensor1* tensor2)
print(tensor1.type())
print(tensor1.dtype)


tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
torch.LongTensor
torch.int64


### Our first neural network


In [13]:
input_tensor = torch.tensor([[0.2423, 0.8303, 0.6788]])

In [16]:
linear_layer = nn.Linear(in_features=3, out_features=2)
output_tensor = linear_layer(input_tensor)

In [17]:
print(output_tensor)

tensor([[-0.2071, -0.3677]], grad_fn=<AddmmBackward0>)


In [19]:
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.5398,  0.3721, -0.1958],
        [-0.3680, -0.4139,  0.3062]], requires_grad=True)
Parameter containing:
tensor([-0.2524, -0.1427], requires_grad=True)


In [21]:
model = nn.Sequential(
    nn.Linear(10, 18),
    nn.Linear(18,20),
    nn.Linear(20,5))

In [22]:
input_tensor = torch.tensor([[0.2423, 0.8303, 0.6788, 0.2739, 0.2938, 0.6578, 0.9597, 0.6992, 0.6523, 0.5678]])

output_tensor = model(input_tensor)
print   (output_tensor)

tensor([[-0.0161,  0.0421, -0.0339,  0.2535,  0.2288]],
       grad_fn=<AddmmBackward0>)


In [4]:
#create a DataFrame
import pandas as pd


In [10]:
data = {
    'name': ['John', 'Anna', 'Peter', 'Linda'],
    'location': ['New York', 'Paris', 'Berlin', 'London'],
    'age': [24, 13, 53, 33]
}

df = pd.DataFrame(data)

df

name  location  age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

In [12]:
df['location'] = df['location'] + 1

TypeError: can only concatenate str (not "int") to str